### ISSUE TITLE
UBUNTU_IMG_VERSION: Ubuntu 19.04 has reached EOL

### ISSUE THREAD

**Issue by iiegn** [thorsten-winkler/docker-texlive#2]
In January Ubuntu 19.04 reached its End of Life: https://lists.ubuntu.com/archives/ubuntu-announce/2020-January/000253.html

Consequently, the default ` ARG UBUNTU_IMG_VERSION` should be changed.
https://github.com/thorsten-winkler/docker-texlive/blob/0d12315147ee8a4bc622a4d7a6962195d5e451ef/2020/Dockerfile.minimal#L6

**Comment by thowdev** [comment]
Thx for the hint. 
I adapted the Docker images now...
(And in near future I will update the "dockerhub test hook" to check that, so that I won't forget that in future :-) )
